# dynmap-mobs configuration
#
general:
  # Whether to check for updates
  update-check: true

# Toggle debug logs
debug:
  # Log everything. Warning: a lot
  all: false

update:
  # Seconds between position updates for mobs
  period: 5.0
  # Round position to given unit
  resolution: 1.0
  # Make markers hidden when they are inside/underground/in shadows (#=light level: 0=full shadow,15=sky(disable hide))
  hideifshadow: 4
  # Make markers hidden when they are under cover (#=sky light level,0=underground,15=open to sky(disable hide))
  hideifundercover: 15
  # Entity updates per tick (prevent lag spikes when large number of entities)
  updates-per-tick: 20

# Enable or disable hostile mobs
hostile:
  blaze: true
  cavespider: true
  chickenjockeydrowned: true
  chickenjockeyhusk: true
  chickenjockeyzombie: true
  chickenjockeyzombievillager: true
  creeper: true
  drowned: true
  elderguardian: true
  enderdragon: true
  enderman: true
  endermite: true
  evoker: true
  ghast: true
  giant: true
  guardian: true
  hoglin: true
  husk: true
  illusioner: true
  magmacube: true
  phantom: true
  piglin: true
  piglinbrute: true
  pillager: true
  ravager: true
  shulker: true
  silverfish: true
  skeleton: true
  slime: true
  spider: true
  spiderjockey: true
  stray: true
  vex: true
  vindicator: true
  warden: true
  witch: true
  wither: true
  witherskeleton: true
  zoglin: true
  zombie: true
  zombievillager: true

# Enable or disable passive mobs
passive:
  allay: true
  axolotl: true
  bat: true
  bee: true
  cat: true
  chicken: true
  chickenjockeyzombifiedpiglin: true
  cod: true
  cow: true
  dolphin: true
  donkey: true
  frog: true
  fox: true
  glowsquid: true
  goat: true
  horse: true
  irongolem: true
  llama: true
  mule: true
  mushroomcow: true
  ocelot: true
  panda: true
  parrot: true
  pig: true
  polarbear: true
  pufferfish: true
  rabbit: true
  salmon: true
  sheep: true
  skeletonhorse: true
  snowman: true
  squid: true
  strider: true
  tadpole: true
  tamedcat: true
  tameddonkey: true
  tamedhorse: true
  tamedllama: true
  tamedmule: true
  tamedparrot: true
  tamedskeletonhorse: true
  tamedtraderllama: true
  tamedwolf: true
  traderllama: true
  tropicalfish: true
  turtle: true
  villager: true
  wanderingtrader: true
  wolf: true
  zombiehorse: true
  zombifiedpiglin: true

# Enable or disable vehicles
vehicle:
  # Specific minecart types
  minecart: false
  minecartchest: false
  minecartcommand: false
  minecartfurnace: false
  minecarthopper: false
  minecartmobspawner: false
  minecarttnt: false
  # Boats
  boat: false
  chestboat: false
  
# Configure layer for hostile mobs
hostilelayer:
  name: "Hostile Mobs"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 10
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false

# Configure layer for passive mobs
passivelayer:
  name: "Passive Mobs"
  # Make mobs layer hidden by default
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 10
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false

# Configure layer for vehicles
vehiclelayer:
  name: "Vehicles"
  hidebydefault: false
  # ordering priority in layer menu (low goes before high - default is 0)
  layerprio: 11
  # (optional) if true, use tiny marker icons (8x8) - default is 16x16
  tinyicons: false
  # (optional) if true, don't show labels on mob icons
  nolabels: false
  # (optional) set minimum zoom level when mob icons should be visible (0=default, any zoom)
  minzoom: 0
  # (optional) include coordinate in label for icon
  inc-coord: false
  
